### ISSUE TITLE
Несовпадение задекларированного в api и действительного тела ответа (null значения полей title и description в ответе)

### ISSUE THREAD

**Issue by oprimolenny** [Witerium/stuffEngine#9]
@RequestMapping(name = "3", method = RequestMethod.PUT, consumes = {"application/json"} )
    public ResponseEntity<?> editEmployee(@Valid @RequestBody Employee employee, HttpServletRequest request)throws IOException{
        logger.info("Получен request на изменение сотрудника: " + employee);
        Employee emp = employeeService.changeEmployee(employee);
        logger.info("Измененный сотрудник: " + emp);
        return new ResponseEntity<>(emp , HttpStatus.OK);
    }

**Comment by oprimolenny** [comment]
потому что в методе public Employee changeEmployee(Employee employee) класса EmployeeServiceImpl переменной updateEmpH не назначается Grade и Position

**Comment by oprimolenny** [comment]
решается повторным считыванием updatedEmpH = employeeDao.read(updatedEmpH.getEmpID()) перед конвертацией updatedEmpH из EmployeeHistory в Employee в методе public Employee changeEmployee(Employee employee) класса EmployeeServiceImpl

**Comment by Witerium** [comment]
Добавлено
